# **JSON file**

# **1) Import Pandas**

In [2]:
import pandas as pd

# **2) Opening a local JSON file**

In [6]:
df = pd.read_json('test.json')
df

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

# **3) Gathering json data from api url**

In [8]:
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"
df = pd.read_json(url)
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

# **SQL file**

# **1) Opening local SQL file**

In [12]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in .\anaconda3\envs\Yeaser\Lib\site-packages (2.2.9)

#### **Download XAMPP software and turn on the apache and mysql server there.**
#### **Navigate to http://localhost/phpmyadmin from browser.**
#### **Create a new database and upload your sql file there.**
#### **Then go on with the followings.**

In [16]:
import mysql.connector

conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [23]:
pd.read_sql_query("SELECT * FROM city WHERE name LIKE 'Kabul'",conn)

C:\Users\USER\AppData\Local\Temp\ipykernel_25588\1984520680.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE name LIKE 'Kabul'",conn)

   ID   Name CountryCode District  Population
0   1  Kabul         AFG    Kabol     1780000

In [24]:
!pip install SQLAlchemy pymysql

Collecting SQLAlchemy
  Downloading sqlalchemy-2.1.6-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\envs\Yeaser\Lib\site-packages (from SQLAlchemy) (4.16.0)
Downloading sqlalchemy-2.1.6-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ------------------------- -------------- 1.6/2.4 MB 9.5 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 10.6 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 3.4 MB/s  0:00:00
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: SQLAlchemy, pymysql

   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   ---------------------------------------- 0/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [pymysql]
   -------------------- ------------------- 1/2 [pymysql]
   -------------------- ------------------- 1/2 [pymysql]
   -------------------- ------------------- 1/2 [pymysql]
   ---------------------------------------- 2/2 [pymysql]

Successfully installed SQLAlchemy-2.1.6 pymysql-1.2.3

In [26]:
import pandas as pd
from sqlalchemy import create_engine

# SQLAlchemy ইঞ্জিন তৈরি করা (ইউজারনেম, পাসওয়ার্ড, হোস্ট এবং ডেটাবেজের নাম ঠিকমতো বসিয়ে দেবেন)
# যদি পাসওয়ার্ড না থাকে, তবে password অংশটি ফাঁকা বা বাদ দিতে পারেন
engine = create_engine("mysql+pymysql://root:@localhost/world")

# এখন pandas দিয়ে কুয়েরি চালানো (কোনো ওয়ার্নিং ছাড়াই কাজ করবে)
df = pd.read_sql_query("SELECT * FROM city WHERE name LIKE 'Kabul'", engine)

df

   ID   Name CountryCode District  Population
0   1  Kabul         AFG    Kabol     1780000

#### **We can use